---
title: "Introduction to BYUImachine"
author: "Brad Borget, Spencer Cook, Chad Schaeffer, Nic Stover, Dallin Webb"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

> Audience:: Future Interns?

## BYUIMachine Learning Tools

This package is created for Henry Schein to create a machine learning model that accurately predicts the output.







Vignettes are long form documentation commonly included in packages. Because they are part of the distribution of the package, they need to be as compact as possible. The `html_vignette` output type provides a custom style sheet (and tweaks some options) to ensure that the resulting html is as small as possible. The `html_vignette` format:
The **BYUImachine** package provides several functions to be utilized to detect and prevent attrition. 

Produce a robust prediction model using machine learning to predict attrition of eClaims customers.

## Data

Data for these functions are assumed to be produced from the `tsCogs` package developed at Henry Schein. 

The data ...

<br>

## Pre Processing

Focuses on reducing columns, but not transforming values. Values should be transofrmed in the train functions so their interpretations can be translated back to understandability. 

* Insert gif

<br>

## Modeling

Training with the caret package to select optimal models to ultimatly suggest to stake holder as well as providing an ensemble model for use in predicting attrition of new data.

Function to produce a table displaying diagnostics for each model, where each row represents a model (labeled by the 
caret method used to create the model) and each column is some measure of performance (as included in the caret
confusionMatrix function)

* Accuracy
* ...

<br>

## Tables

* Each model run diagnostics
* Predictions for each ID to search for general model consensus


## Predicting

Function that puts the model to use.

* better to not detect dropping clients than to label healthy clients as dropping.

> Do you want the model ready to go in package? Or a list of suggested models to pick from.

<br>

## Visualization

Function that produces trelliscope visualizations of each feature's class distribution (usefullness). 

Function also provides model diagnostics like ROC curves etc. 

> Show from laptop

<br>

<br>
