#' @importFrom utils globalVariables
globalVariables(
  c(".",
    "d",
    "Overall",
    "rowname",
    "imp_list",
    "features",
    "rank_inverse",
    "n",
    "rank_multiplied",
    "ID",
    "rank_scaled",
    "features",
    "measure",
    "name",
    "features",
    "percent_common",
    "test_x",
    "test_y",
    "score",
    "method"
    )
  )
